"""add is_active to students

Revision ID: 4ef10b610bcf
Revises: a8eadbf4ded4
Create Date: 2026-06-25 22:03:13.491345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef10b610bcf'
down_revision: Union[str, Sequence[str], None] = 'a8eadbf4ded4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('students_dept_id_fkey'), 'students', type_='foreignkey')
    op.drop_column('students', 'dept_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('dept_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('students_dept_id_fkey'), 'students', 'departments', ['dept_id'], ['dept_id'])
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
